import { FACILITY, type WorkOrderDraft } from "./scenarios";

export const PLANNING_RECIPIENTS = [
  "maintenance.planning@rheinland.shell.com",
  "rot-mechanical@rheinland.shell.com",
  "sap-pm-notifications@rheinland.shell.com",
];

function formatTs(iso: string): string {
  return new Date(iso).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function buildWorkOrderDocumentHtml(
  workOrder: WorkOrderDraft,
  opts: { sapNumber: string; engineerNotes?: string; reelinId?: string }
): string {
  const notesBlock = opts.engineerNotes
    ? `<section><h2>Engineer notes</h2><p>${opts.engineerNotes.replace(/\n/g, "<br/>")}</p></section>`
    : "";

  const ops = workOrder.operations
    .map((o) => `<tr><td>${o.op}</td><td>${o.description}</td><td>${o.duration}h</td></tr>`)
    .join("");

  const parts = workOrder.spareParts
    .map((p) => `<tr><td>${p.material}</td><td>${p.qty}</td><td>${p.status}</td></tr>`)
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>SAP PM Work Order ${opts.sapNumber}</title>
  <style>
    body { font-family: "IBM Plex Sans", Arial, sans-serif; font-size: 12px; color: #1a1f26; margin: 32px; }
    h1 { font-size: 18px; margin: 0 0 4px; }
    h2 { font-size: 13px; margin: 20px 0 8px; text-transform: uppercase; letter-spacing: 0.04em; color: #5c6570; }
    .meta { color: #5c6570; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #c8cdd5; padding: 6px 8px; text-align: left; }
    th { background: #f7f8fa; font-weight: 600; }
    .footer { margin-top: 32px; font-size: 10px; color: #8b939e; border-top: 1px solid #dde1e8; padding-top: 12px; }
    @media print { body { margin: 16px; } }
  </style>
</head>
<body>
  <h1>SAP PM Work Order · ${opts.sapNumber}</h1>
  <p class="meta">${FACILITY.name} (${FACILITY.code}) · Generated by Operadroom · ${formatTs(new Date().toISOString())}</p>

  <section>
    <h2>Header</h2>
    <p><strong>Equipment</strong> · ${workOrder.equipment}</p>
    <p><strong>Functional location</strong> · ${workOrder.functionalLocation}</p>
    <p><strong>Order type</strong> · ${workOrder.orderType}</p>
    <p><strong>Priority</strong> · ${workOrder.priority}</p>
    <p><strong>Planner group</strong> · ${workOrder.plannerGroup}</p>
    <p><strong>Work center</strong> · ${workOrder.workCenter}</p>
    <p><strong>Short text</strong> · ${workOrder.shortText}</p>
    <p><strong>Long text</strong> · ${workOrder.longText}</p>
    <p><strong>Required start</strong> · ${formatTs(workOrder.requiredStart)}</p>
    <p><strong>Required end</strong> · ${formatTs(workOrder.requiredEnd)}</p>
    <p><strong>Estimated hours</strong> · ${workOrder.estimatedHours}</p>
  </section>

  ${notesBlock}

  <section>
    <h2>Operations</h2>
    <table><thead><tr><th>Op</th><th>Description</th><th>Duration</th></tr></thead><tbody>${ops}</tbody></table>
  </section>

  <section>
    <h2>Spare parts</h2>
    <table><thead><tr><th>Material</th><th>Qty</th><th>Status</th></tr></thead><tbody>${parts}</tbody></table>
  </section>

  <section>
    <h2>Safety</h2>
    <ul>${workOrder.safetyNotes.map((n) => `<li>${n}</li>`).join("")}</ul>
  </section>

  <div class="footer">
    ${opts.reelinId ? `Reelin ID · ${opts.reelinId}<br/>` : ""}
    DRAFT/RELEASE simulation — Operadroom pilot sandbox
  </div>
</body>
</html>`;
}

export function exportWorkOrderPdf(
  workOrder: WorkOrderDraft,
  opts: { sapNumber: string; engineerNotes?: string; reelinId?: string }
): void {
  const html = buildWorkOrderDocumentHtml(workOrder, opts);
  const win = window.open("", "_blank", "noopener,noreferrer");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  window.setTimeout(() => win.print(), 350);
}

export function downloadWorkOrderHtml(
  workOrder: WorkOrderDraft,
  opts: { sapNumber: string; engineerNotes?: string; reelinId?: string }
): void {
  const html = buildWorkOrderDocumentHtml(workOrder, opts);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `WO-${opts.sapNumber}-Rheinland.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function emailWorkOrderToPlanning(
  workOrder: WorkOrderDraft,
  opts: { sapNumber: string; engineerNotes?: string; reelinId?: string }
): Promise<{ sentAt: string; recipients: string[]; messageId: string }> {
  await new Promise((r) => setTimeout(r, 1400));
  return {
    sentAt: new Date().toISOString(),
    recipients: PLANNING_RECIPIENTS,
    messageId: `rhn-mime-${opts.sapNumber}-${Date.now().toString(36)}`,
  };
}
